apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-app-tls
spec:
  secretName: demo-app-tls
  dnsNames:
  - kubecon.152.42.158.33.nip.io  # Replace with your domain
  issuerRef:
    name: demo-issuer
    kind: Issuer
